# Generated by Django 2.1.2 on 2018-10-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myadminpanel',
            name='app_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
